config/routes.rb
Rails.application.routes.draw do
  
  root 'home#index'
  get '/:locale', to: 'home#index'

  scope '/(:locale)', locale: /en|fr|pt/ do    
    get 'a2c', to: "reports#index"
    resources :reports, path: '/a2c/reports'

    # for A2C service related api 
    get 'a2c/:action',controller: :a2c
  end

end

app/models/report.rb
class Report < ActiveRecord::Base
  paginates_per 20
  default_scope { order('created_at DESC') }
  
  enum property_type: {house: 0,  flat: 1}
end

app/controllers/a2c_controller.rb
class A2cController  < ApplicationController

	# API 
	def stats
		data = {
			median_price: rand(1000),
			on_market_similar_props: rand(1000),
			sold_similar_props: rand(1000),			
		}
		render json:  data.to_json
	end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :set_locale
  protect_from_forgery with: :exception

  def default_url_options(options = {})
    { locale: I18n.locale }.merge options
  end

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: [:show, :edit, :update, :destroy]

  def index
    @reports = has_search_params? ? filter_search : Report.all
    @reports = @reports.page(params[:page]) if @reports.any?
  end

  def show
  end

  def new
    @report = Report.new
  end

  def edit
  end

  def create
    @report = Report.new(report_params)
    respond_to do |format|
      if @report.save
        format.html { redirect_to @report, notice: 'Report was successfully created.' }
        format.json { render :show, status: :created, location: @report }
      else
        format.html { render :new }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { render nothing: true, status: :ok }
      else
        format.html { render :edit }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to properties_url, notice: 'Report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def set_report
    @report = Report.find(params[:id])
  end

  def report_params
    params.require(:report).permit(:report_type,
                                     :rooms,
                                     :address,
                                     :surface,
                                     :price,
                                     :city,
                                     :description,
                                     :name,
                                     :phone,
                                     :email,
                                     :lat,
                                     :lng)
  end

  def filter_search
    name        = params[:contact_name]
    to_date     = parse_date(params[:to_date])
    from_date   = parse_date(params[:from_date])
    valid_dates = valid_dates?(from_date, to_date)

    if name.present? && valid_dates
      Report
        .where("name ILIKE ?", "%#{name}%")
        .where(created_at: range(from_date, to_date))
    elsif name.blank? && valid_dates
      Report
        .where(created_at: range(from_date, to_date))
    elsif name.present?
      Report
        .where("name ILIKE ?", "%#{name}%")
    else
      Report.all
    end
  end

  def range(from, to)
    (from.beginning_of_day)..(to.end_of_day)
  end

  def parse_date(date)
    DateTime.parse(date)
  rescue
    nil
  end

  def valid_dates?(from, to)
    from.present? && to.present? && from <= to
  end

  def has_search_params?
    params[:contact_name].present? || (params[:to_date].present? && params[:from_date].present?)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def type_name(type_i)
    #puts type_i
    t(type_i) #if == Report.property_type[:house]
    #t('flat')  if type_i == Report.property_type[:flat]
  end
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/home/index.slim
 
h1
  A2C Service 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html moznomarginboxes mozdisallowselectionprint>
<head>
  <title>PrintReport</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  
  <!-- Custom CSS -->
  <%= stylesheet_link_tag    'style', media: 'all' %>
  <%= stylesheet_link_tag    'print', media: 'print' %>
  <!-- Bootstrap -->
  <script src="https://www.atlasestateagents.co.uk/javascript/tether.min.js"></script>
  <%= stylesheet_link_tag    'vendor/bootstrap.min' %>
  <%= javascript_include_tag 'vendor/bootstrap.min' %>
  <!-- AngularJS -->
  <%= javascript_include_tag 'vendor/angular.min' %>
  <script type='text/javascript' src='/index_files/wz_jsgraphics.js'></script>
  <!-- External -->
  <link href='https://fonts.googleapis.com/css?family=Lato:400,100,300,700' rel='stylesheet' type='text/css'>
<style type="text/css">
<!--
span.cls_003{font-family:Arial,serif;font-size:14.1px;color:rgb(254,255,255);font-weight:bold;font-style:normal;text-decoration: none}
div.cls_003{font-family:Arial,serif;font-size:14.1px;color:rgb(254,255,255);font-weight:bold;font-style:normal;text-decoration: none}
span.cls_004{font-family:Arial,serif;font-size:14.1px;color:rgb(254,255,255);font-weight:normal;font-style:normal;text-decoration: none}
div.cls_004{font-family:Arial,serif;font-size:14.1px;color:rgb(254,255,255);font-weight:normal;font-style:normal;text-decoration: none}
span.cls_002{font-family:Arial,serif;font-size:60.0px;color:rgb(0,104,144);font-weight:bold;font-style:normal;text-decoration: none}
div.cls_002{font-family:Arial,serif;font-size:60.0px;color:rgb(0,104,144);font-weight:bold;font-style:normal;text-decoration: none}
span.cls_005{font-family:Arial,serif;font-size:18.1px;color:rgb(0,104,144);font-weight:normal;font-style:normal;text-decoration: none}
div.cls_005{font-family:Arial,serif;font-size:18.1px;color:rgb(0,104,144);font-weight:normal;font-style:normal;text-decoration: none}
span.cls_006{font-family:Arial,serif;font-size:12.1px;color:rgb(0,104,144);font-weight:normal;font-style:normal;text-decoration: none}
div.cls_006{font-family:Arial,serif;font-size:12.1px;color:rgb(0,104,144);font-weight:normal;font-style:normal;text-decoration: none}
span.cls_007{font-family:Arial,serif;font-size:12.1px;color:rgb(0,104,144);font-weight:bold;font-style:normal;text-decoration: none}
div.cls_007{font-family:Arial,serif;font-size:12.1px;color:rgb(0,104,144);font-weight:bold;font-style:normal;text-decoration: none}
span.cls_008{font-family:Arial,serif;font-size:14.1px;color:rgb(0,104,144);font-weight:normal;font-style:normal;text-decoration: none}
div.cls_008{font-family:Arial,serif;font-size:14.1px;color:rgb(0,104,144);font-weight:normal;font-style:normal;text-decoration: none}
span.cls_009{font-family:Arial,serif;font-size:14.1px;color:rgb(0,104,144);font-weight:bold;font-style:normal;text-decoration: none}
div.cls_009{font-family:Arial,serif;font-size:14.1px;color:rgb(0,104,144);font-weight:bold;font-style:normal;text-decoration: none}
span.cls_010{font-family:Arial,serif;font-size:14.1px;color:rgb(18,100,143);font-weight:bold;font-style:normal;text-decoration: none}
div.cls_010{font-family:Arial,serif;font-size:14.1px;color:rgb(18,100,143);font-weight:bold;font-style:normal;text-decoration: none}
span.cls_011{font-family:Arial,serif;font-size:14.1px;color:rgb(18,100,143);font-weight:normal;font-style:normal;text-decoration: none}
div.cls_011{font-family:Arial,serif;font-size:14.1px;color:rgb(18,100,143);font-weight:normal;font-style:normal;text-decoration: none}
span.cls_012{font-family:Arial,serif;font-size:10.1px;color:rgb(18,100,143);font-weight:normal;font-style:normal;text-decoration: none}
div.cls_012{font-family:Arial,serif;font-size:10.1px;color:rgb(18,100,143);font-weight:normal;font-style:normal;text-decoration: none}
span.cls_013{font-family:Arial,serif;font-size:14.1px;color:rgb(43,42,41);font-weight:bold;font-style:normal;text-decoration: none}
div.cls_013{font-family:Arial,serif;font-size:14.1px;color:rgb(43,42,41);font-weight:bold;font-style:normal;text-decoration: none}
span.cls_014{font-family:Arial,serif;font-size:12.1px;color:rgb(43,42,41);font-weight:normal;font-style:normal;text-decoration: none}
div.cls_014{font-family:Arial,serif;font-size:12.1px;color:rgb(43,42,41);font-weight:normal;font-style:normal;text-decoration: none}
span.cls_015{font-family:Times,serif;font-size:12.1px;color:rgb(43,42,41);font-weight:normal;font-style:normal;text-decoration: none}
div.cls_015{font-family:Times,serif;font-size:12.1px;color:rgb(43,42,41);font-weight:normal;font-style:normal;text-decoration: none}
span.cls_016{font-family:Arial,serif;font-size:14.1px;color:rgb(43,42,41);font-weight:normal;font-style:normal;text-decoration: none}
div.cls_016{font-family:Arial,serif;font-size:14.1px;color:rgb(43,42,41);font-weight:normal;font-style:normal;text-decoration: none}
span.cls_017{font-family:Arial,serif;font-size:11.1px;color:rgb(43,42,41);font-weight:normal;font-style:normal;text-decoration: none}
div.cls_017{font-family:Arial,serif;font-size:11.1px;color:rgb(43,42,41);font-weight:normal;font-style:normal;text-decoration: none}
span.cls_018{font-family:Arial,serif;font-size:18.1px;color:rgb(254,255,255);font-weight:bold;font-style:normal;text-decoration: none}
div.cls_018{font-family:Arial,serif;font-size:18.1px;color:rgb(254,255,255);font-weight:bold;font-style:normal;text-decoration: none}
span.cls_019{font-family:Arial,serif;font-size:18.1px;color:rgb(254,255,255);font-weight:normal;font-style:normal;text-decoration: none}
div.cls_019{font-family:Arial,serif;font-size:18.1px;color:rgb(254,255,255);font-weight:normal;font-style:normal;text-decoration: none}
span.cls_020{font-family:Arial,serif;font-size:12.1px;color:rgb(254,255,255);font-weight:bold;font-style:normal;text-decoration: none}
div.cls_020{font-family:Arial,serif;font-size:12.1px;color:rgb(254,255,255);font-weight:bold;font-style:normal;text-decoration: none}
span.cls_021{font-family:Arial,serif;font-size:12.1px;color:rgb(254,255,255);font-weight:normal;font-style:normal;text-decoration: none}
div.cls_021{font-family:Arial,serif;font-size:12.1px;color:rgb(254,255,255);font-weight:normal;font-style:normal;text-decoration: none}
span.cls_022{font-family:Arial,serif;font-size:16.1px;color:rgb(227,142,57);font-weight:bold;font-style:normal;text-decoration: none}
div.cls_022{font-family:Arial,serif;font-size:16.1px;color:rgb(227,142,57);font-weight:bold;font-style:normal;text-decoration: none}
span.cls_024{font-family:Arial,serif;font-size:16.1px;color:rgb(0,104,144);font-weight:bold;font-style:normal;text-decoration: none}
div.cls_024{font-family:Arial,serif;font-size:16.1px;color:rgb(0,104,144);font-weight:bold;font-style:normal;text-decoration: none}
span.cls_025{font-family:Arial,serif;font-size:11.1px;color:rgb(43,42,41);font-weight:bold;font-style:normal;text-decoration: none}
div.cls_025{font-family:Arial,serif;font-size:11.1px;color:rgb(43,42,41);font-weight:bold;font-style:normal;text-decoration: none}
span.cls_026{font-family:Arial,serif;font-size:8.5px;color:rgb(43,42,41);font-weight:normal;font-style:normal;text-decoration: none}
div.cls_026{font-family:Arial,serif;font-size:8.5px;color:rgb(43,42,41);font-weight:normal;font-style:normal;text-decoration: none}
span.cls_027{font-family:Arial,serif;font-size:8.4px;color:rgb(43,42,41);font-weight:normal;font-style:normal;text-decoration: none}
div.cls_027{font-family:Arial,serif;font-size:8.4px;color:rgb(43,42,41);font-weight:normal;font-style:normal;text-decoration: none}
span.cls_028{font-family:Arial,serif;font-size:20.1px;color:rgb(43,42,41);font-weight:normal;font-style:normal;text-decoration: none}
div.cls_028{font-family:Arial,serif;font-size:20.1px;color:rgb(43,42,41);font-weight:normal;font-style:normal;text-decoration: none}
span.cls_029{font-family:Arial,serif;font-size:12.1px;color:rgb(43,42,41);font-weight:bold;font-style:normal;text-decoration: none}
div.cls_029{font-family:Arial,serif;font-size:12.1px;color:rgb(43,42,41);font-weight:bold;font-style:normal;text-decoration: none}
span.cls_030{font-family:Arial,serif;font-size:8.1px;color:rgb(43,42,41);font-weight:normal;font-style:normal;text-decoration: none}
div.cls_030{font-family:Arial,serif;font-size:8.1px;color:rgb(43,42,41);font-weight:normal;font-style:normal;text-decoration: none}
span.cls_031{font-family:Arial,serif;font-size:18.1px;color:rgb(43,42,41);font-weight:bold;font-style:normal;text-decoration: none}
div.cls_031{font-family:Arial,serif;font-size:18.1px;color:rgb(43,42,41);font-weight:bold;font-style:normal;text-decoration: none}
span.cls_032{font-family:Arial,serif;font-size:15.1px;color:rgb(43,42,41);font-weight:normal;font-style:normal;text-decoration: none}
div.cls_032{font-family:Arial,serif;font-size:15.1px;color:rgb(43,42,41);font-weight:normal;font-style:normal;text-decoration: none}
-->
</style>
  <%= csrf_meta_tags %>
  <%= yield :head %>
</head>
<body>
<nav class="navbar navbar-fixed-top navbar-dark bg-inverse">
  <%= link_to 'Print Report', root_path, class: 'navbar-brand' %>
   <ul class="nav navbar-nav">
    <li class="nav-item <%= 'active' if current_page?(reports_path) %>">
      <%= link_to t('reports'), reports_path, class: 'nav-link' %>
    </li>
  </ul>
  <ul class="nav navbar-nav pull-xs-right">
    <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Language</a>
    <div class="dropdown-menu">
      <%#= link_to "English"  , params.merge(locale: :en), class: 'dropdown-item' %>
      <%= link_to "Français" , params.merge(locale: :fr), class: 'dropdown-item' %>
      <%= link_to "Português", params.merge(locale: :pt), class: 'dropdown-item' %>
    </div>
    </li>
  </ul>
</nav>
<div class="container-fluid">
  <%= yield %>
</div>
</body>
</html>

app/views/reports/_form.slim
= content_for :head 
  = javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=AIzaSyDWif-Vrje2gPVDFGFWcUytgJmZxUMQlRU&libraries=places"
  = javascript_include_tag 'address_complete'

= form_for(@report) do |f|
  - if @report.errors.any?
    #error_explanation
      h2
        = pluralize(@report.errors.count, "error")
        | prohibited this report from being saved:
      ul
        - @report.errors.full_messages.each do |message|
          li= message
  fieldset.form-group
    label = t('property_type')
    .radio
      label
        = f.radio_button :property_type, Report.property_types.keys[0]
        = t('house')
    .radio
      label
        = f.radio_button :property_type, Report.property_types.keys[1]
        = t('flat')
  .form-group
    = f.label :rooms, t('rooms')
    = f.number_field :rooms, class: 'form-control'
  .form-group
    = f.label :description, t('description')
    = f.text_field :description, class: 'form-control'
  .form-group
    = f.label :city, t('city')
    = f.text_field :city, class: 'form-control'
  .form-group
    = f.label :address, t('address')
    = f.text_field :address, class: 'form-control', id: 'address_field'
  .form-group
    = f.label :surface, t('surface')
    = f.number_field :surface, class: 'form-control'
  .form-group
    = f.label :price, t('price')
    = f.text_field :price, class: 'form-control'
  fieldset
    legend = t('owner')
    .form-group
      = f.label :name, t('name')
      = f.text_field :name, class: 'form-control'
    .form-group
      = f.label :phone, t('phone')
      = f.text_field :phone, class: 'form-control'
    .form-group
      = f.label :email, t('email')
      = f.text_field :email, class: 'form-control'

    = f.hidden_field :lat, value: 0, id: 'latitude_field'
    = f.hidden_field :lng, value: 0, id: 'longitude_field'

  .actions
    = f.submit t('actions.create'), class: 'btn btn-primary'

app/views/reports/_page_2.slim
div style="position:absolute;left:50%;margin-left:-297px;top:851px;width:595px;height:841px;border-style:outset;overflow:hidden" 
  div style="position:absolute;left:0px;top:0px" 
    img height="841" src="/index_files/background2.jpg" width="595" /
  .cls_003 style="position:absolute;left:303.77px;top:24.25px" 
    span.cls_003 ANALYSE
    span.cls_004 DE CONTEXTE CONCURRENTIEL
  .cls_013 style="position:absolute;left:28.35px;top:370.34px" 
    span.cls_013 Maison
  .cls_013 style="position:absolute;left:277.80px;top:370.34px" 
    span.cls_013 Description du bien :
  .cls_014 style="position:absolute;left:277.80px;top:386.74px" 
    span.cls_014 Lorem ipsum dolor sit amet, consectetur adipiscing
  .cls_014 style="position:absolute;left:32.35px;top:389.66px" 
    span.cls_014 Adresse :
  .cls_014 style="position:absolute;left:93.26px;top:389.66px" 
    span.cls_014 49, rue de la République
  .cls_014 style="position:absolute;left:277.80px;top:401.14px" 
    span.cls_014 elit, sed do eiusmod tempor incididunt ut labore et
  .cls_014 style="position:absolute;left:93.26px;top:404.06px" 
    span.cls_014 77000 Melun
  .cls_014 style="position:absolute;left:277.80px;top:415.54px" 
    span.cls_014 dolore magna aliqua. Ut enim ad minim veniam, quis
  .cls_014 style="position:absolute;left:277.80px;top:429.94px" 
    span.cls_014 nostrud exercitation ullamco laboris nisi ut aliquip ex
  .cls_014 style="position:absolute;left:32.35px;top:435.53px" 
    span.cls_014 Pièces :
  .cls_015 style="position:absolute;left:93.26px;top:435.19px" 
    span.cls_015 7
  .cls_014 style="position:absolute;left:277.80px;top:444.34px" 
    span.cls_014 ea commodo consequat.
  .cls_014 style="position:absolute;left:32.35px;top:452.61px" 
    span.cls_014 Surface :
  .cls_014 style="position:absolute;left:93.26px;top:452.61px" 
    span.cls_014 150m²
  .cls_013 style="position:absolute;left:277.80px;top:473.54px" 
    span.cls_013 Description du secteur :
  .cls_014 style="position:absolute;left:277.80px;top:489.94px" 
    span.cls_014 Duis aute irure dolor in reprehenderit in voluptate
  .cls_014 style="position:absolute;left:277.80px;top:504.34px" 
    span.cls_014 velit esse cillum dolore eu fugiat nulla pariatur. Ex-
  .cls_014 style="position:absolute;left:277.80px;top:518.74px" 
    span.cls_014 cepteur sint occaecat cupidatat non proident, sunt in
  .cls_014 style="position:absolute;left:277.80px;top:533.14px" 
    span.cls_014 culpa qui officia deserunt mollit anim id est laborum.
  .cls_014 style="position:absolute;left:28.35px;top:579.41px" 
    span.cls_014 Propriétaire
  .cls_013 style="position:absolute;left:303.89px;top:578.12px" 
    span.cls_013 - Notre méthodologie d’analyse -
  .cls_016 style="position:absolute;left:28.35px;top:594.21px" 
    span.cls_016 M.
    span.cls_013 François Durand
  .cls_017 style="position:absolute;left:278.50px;top:608.72px" 
    span.cls_017 Sed ut perspiciatis unde omnis iste natus error sit
  .cls_014 style="position:absolute;left:28.35px;top:610.61px" 
    span.cls_014 49, rue de la République
  .cls_017 style="position:absolute;left:278.50px;top:621.92px" 
    span.cls_017 voluptatem accusantium doloremque laudantium,
  .cls_014 style="position:absolute;left:28.35px;top:625.01px" 
    span.cls_014 7700 Melun
  .cls_017 style="position:absolute;left:278.50px;top:635.12px" 
    span.cls_017 totam rem aperiam, eaque ipsa quae ab illo inventore
  .cls_014 style="position:absolute;left:28.35px;top:639.41px" 
    span.cls_014 T. 06.49.03.34.45
  .cls_017 style="position:absolute;left:278.50px;top:648.32px" 
    span.cls_017 veritatis et quasi architecto beatae vitae dicta sunt ex-
  .cls_014 style="position:absolute;left:28.35px;top:653.81px" 
    span.cls_014 E. françois.durand@freemail.com
  .cls_017 style="position:absolute;left:278.50px;top:661.52px" 
    span.cls_017 plicabo. Nemo enim ipsam voluptatem quia voluptas
  .cls_017 style="position:absolute;left:278.50px;top:674.72px" 
    span.cls_017 sit aspernatur aut odit aut fugit, sed quia consequun-
  .cls_017 style="position:absolute;left:278.50px;top:687.92px" 
    span.cls_017 tur magni dolores eos qui ratione voluptatem sequi
  .cls_017 style="position:absolute;left:278.50px;top:701.12px" 
    span.cls_017 nesciunt.
  .cls_010 style="position:absolute;left:103.46px;top:773.98px" 
    span.cls_010 David
    span.cls_011 Delacroix
  .cls_012 style="position:absolute;left:379.96px;top:778.12px" 
    span.cls_012 06 44 08 79 88
  .cls_012 style="position:absolute;left:103.46px;top:791.98px" 
    span.cls_012 Conseiller Immobilier chez I@D
  .cls_012 style="position:absolute;left:379.96px;top:793.12px" 
    span.cls_012 david.delacroix@iadfrance.com
  .cls_012 style="position:absolute;left:379.96px;top:808.12px" 
    span.cls_012 Champigny sur Marne

app/views/reports/_page_4.slim
div style="position:absolute;left:50%;margin-left:-297px;top:2553px;width:595px;height:841px;border-style:outset;overflow:hidden" 
  div style="position:absolute;left:0px;top:0px" 
    img height="841" src="/index_files/background4.jpg" width="595" /
  .cls_003 style="position:absolute;left:303.77px;top:24.25px" 
    span.cls_003 ANALYSE
    span.cls_004 DE CONTEXTE CONCURRENTIEL
  .cls_016 style="position:absolute;left:28.35px;top:60.86px" 
    span.cls_016 Analyse du marché local
  .cls_028 style="position:absolute;left:28.35px;top:74.86px" 
    span.cls_028 Evolutions et tendances
  .cls_029 style="position:absolute;left:28.35px;top:134.98px" 
    span.cls_029 Evolution du prix au m²
  .cls_029 style="position:absolute;left:308.03px;top:134.98px" 
    span.cls_029 Distribution des prix au m²
  .cls_029 style="position:absolute;left:28.35px;top:334.92px" 
    span.cls_029 Evolution du nombre de publication
  .cls_029 style="position:absolute;left:308.03px;top:334.92px" 
    span.cls_029 Evolution de la durée de publication moyen
  .cls_029 style="position:absolute;left:27.51px;top:522.39px" 
    span.cls_029 Répartition des durées de publication
  .cls_010 style="position:absolute;left:103.46px;top:773.98px" 
    span.cls_010 David
    span.cls_011 Delacroix
  .cls_012 style="position:absolute;left:379.96px;top:778.12px" 
    span.cls_012 06 44 08 79 88
  .cls_012 style="position:absolute;left:103.46px;top:791.98px" 
    span.cls_012 Conseiller Immobilier chez I@D
  .cls_012 style="position:absolute;left:379.96px;top:793.12px" 
    span.cls_012 david.delacroix@iadfrance.com
  .cls_012 style="position:absolute;left:379.96px;top:808.12px" 
    span.cls_012 Champigny sur Marne

app/views/reports/_page_8.slim
div style="position:absolute;left:50%;margin-left:-297px;top:5957px;width:595px;height:841px;border-style:outset;overflow:hidden" 
  div style="position:absolute;left:0px;top:0px" 
    img height="841" src="/index_files/background8.jpg" width="595" /

app/views/reports/index.slim
h2 = t('properties')
br
= link_to t('actions.new_report'), new_report_path, class: 'btn btn-primary'
br
br
nav.navbar.navbar-light.bg-faded
  form.form-inline.pull-xs-right
    label = t('actions.search') 
      | &nbsp;
    input.form-control name="contact_name" type="Text" placeholder="#{t('contact_name')}"
    | &nbsp;
    .form-group.search-date-fields
      label = t('from_date') 
      input.form-control.form-control-sm name="from_date" type="date"
      | &nbsp;
      label = t('to_date')
      input.form-control.form-control-sm name="to_date" type="date"
    | &nbsp;&nbsp;
    input.btn.btn-primary-outline type="Submit" value="#{t('actions.search')}"
table.table.table-striped
  thead
    tr
      th = t('creation_date') 
      th = t('type')
      th = t('description')
      th = t('city')
      th = t('rooms')
      th = t('address')
      th = t('surface')
      th = t('price')
      th = t('owner')
      th 
  tbody
    - @reports.each do |report|
      tr
        td = report.created_at.strftime('%m/%d/%Y') 
        td = t(report.property_type)
        td = report.description
        td = report.city
        td = report.rooms
        td = report.address
        td = report.surface
        td = report.price
        td 
          dl.dl-horizontal
          dt = t('name')
          dd = report.name
          dt = t('phone')
          dd = report.phone
          dt = t('email')
          dd = report.email
        td
          .btn-group.btn-group-sm 
            = link_to t('actions.print')  , report_path(report, print: true), target: '_blank', class: 'btn btn-info-outline' 
            = link_to t('actions.edit')   , edit_report_path(report), class: 'btn btn-primary-outline'
            = link_to t('actions.destroy'), report, method: :delete , data: { confirm: t('confirm_question') }, class: 'btn btn-danger-outline'
= (paginate @reports) if @reports.any?            
br

app/views/reports/new.html.erb
<br>
<%= link_to t('actions.back'), reports_path %>
<br>
<h2><%= t('actions.new_report') %></h2>

<%= render 'form' %>